### ISSUE TITLE
Dependency bounds too restrictive for modern snapshots

### ISSUE THREAD

**Issue by ChrisPenner** [rampion/tree-traversals#1]
Hey there! You'll want to take a look and expand your version bounds for this package; it refuses to build on modern stackage LTS's due to bounds:

```
- base (==4.10.*)
- containers (<0.6.0.0) 
```

Cheers!

**Comment by rampion** [comment]
Thanks! Published as v0.1.1.0

**Comment by joncol** [comment]
Hi @rampion, any chance you might update this again to make it work with base 4.16.3.0 etc?

**Comment by rampion** [comment]
Thanks! Published as v0.1.2.0
